name: Core CI Workflow

on:
  workflow_call:

jobs:
  semantic-versioning:
    runs-on: ubuntu-latest
    
    name: Nerdbank.GitVersioning
    # You may pin to the exact commit or the version.
    # uses: dotnet/nbgv@f088059084cb5d872e9d1a994433ca6440c2bf72
    steps:
      - uses: steve-kaschimer/action-semantic-versionsing/action.yml@main #dotnet/nbgv@v0.4.2
        #with:
        #  # The path to the directory for which the version should be determined. This should be at or below the directory containing the version.json file. Default is repo root directory.
        #  path: # optional, default is .
        #  # Defines ALL version variables as environment variables, with a "NBGV_" prefix.
        #  setAllVars: # optional
        #  # Defines a few common version variables as environment variables, with a "Git" prefix (e.g. GitBuildVersion, GitBuildVersionSimple, GitAssemblyInformationalVersion).
        #  setCommonVars: # optional
        #  # The path to a file whose version setting should be changed to match the computed version. Supported file types: `package.json`.
        #  stamp: # optional
        #  # The version of the nbgv dotnet CLI tool to install and use. If not specified, the default is the latest stable version.
        #  toolVersion: # optional
        #  # An additional feed to search for the nbgv dotnet CLI tool. Default feeds may include https://api.nuget.org/v3/index.json or whatever is specified in a nuget.config file at the root of your repo.
        #  toolFeed: # optional
          
  print-build-run-id:
    needs: semantic-versioning
    runs-on: Ubuntu
    steps:
      - name: Get the repo-type custom property
        shell: bash
        run: |
          echo "build_run_id=${{ github.run_id }}"
